MusicInventory/MusicInventory/Models/Music.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicInventory.Models
{
    using System;
    using System.Collections.Generic;

    public class MusicList
    {
        public List<Music> musicList;
        public MusicList()
        {
            musicList = new List<Music>();
        }
    }

    public class Music
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Artist { get; set; }
        public string Genre { get; set; }
        public Nullable<int> Price { get; set; }
        public string ImageUrl { get; set; }

        public int Quantity = 1;
    }
}

MusicInventory/MusicInventory/Controllers/MusicsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MusicInventory.Models;
using Newtonsoft.Json.Linq;

namespace MusicInventory.Controllers
{
    public class MusicsController : Controller
    {
        MusicList musicList = new MusicList();
        Repository ob = new Repository();
        // GET: Musics

        public async Task<ActionResult> Index(string id)
        {
            if (id == null)
                return View(await ob.ToList());
            else
                return View(await ob.GetMusicByGenre(id));
        }

        // GET: Musics/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Music music = await ob.Find(id);
            if (music == null)
            {
                return HttpNotFound();
            }
            return View(music);
        }

        public async Task<ActionResult> DisplayAllGenres()
        {
            var temp = ob.GetAllGenres().Result;
            var res = temp.Result;
            return PartialView("DisplayAllGenres",res);
        }


        public async Task<ActionResult> AddToCart(int id)
        {
            if(Session["Music"]!=null)
            {
                MusicList musicList = (MusicList)Session["Music"];
                musicList.musicList=ob.AddToPurchaseCart(id).Result;
                Session["Music"] = musicList;
            }
            else
            {
                MusicList musicList = new MusicList();
                musicList.musicList = ob.AddToPurchaseCart(id).Result;
                Session["Music"] = musicList;
            }

            return View();
        }
        public ActionResult ShowCart()
        {

            if(Request.IsAjaxRequest())
            {
                if (Session["Music"] != null)
                {
                    musicList = (MusicList)Session["Music"];
                    musicList.musicList = ob.ShowCart();
                    Session["Music"] = musicList;
                }
                else
                {
                    musicList = new MusicList();
                    musicList.musicList = ob.ShowCart();
                    Session["Music"] = musicList;
                }
                return PartialView("ShowCart", musicList);
            }
            else
            {
                if (Session["Music"] != null)
                {
                    musicList = (MusicList)Session["Music"];
                    musicList.musicList = ob.ShowCart();
                    Session["Music"] = musicList;
                }
                else
                {
                    musicList = new MusicList();
                    musicList.musicList = ob.ShowCart();
                    Session["Music"] = musicList;
                }
                return View("ShowCart", musicList);
            }
        }
            
        /*[HttpPost]*/
        public ActionResult DeleteFromCart(int id)
        {
            musicList.musicList = ob.Delete(id);
            return RedirectToAction("ShowCart", musicList);
        }
        public ActionResult CheckOut()
        {
            musicList.musicList = ob.CheckOut();
            return View("CheckOut", musicList);
        }
        public async Task<ActionResult> DeleteAll()
        {
            ob.DeleteAll();
            return View("Index",await ob.ToList());
        }
    }
}

MusicInventory/MusicInventory/Views/Musics/AddToCart.cshtml
@model IEnumerable<MusicInventory.Models.Music>

@{
    ViewBag.Title = "AddToCart";
}

MusicInventory/MusicInventory/Views/Musics/CheckOut.cshtml
@model MusicInventory.Models.MusicList

@{
    ViewBag.Title = "CheckOut";
}

<h2>CheckOut</h2>

<table class="table">
    <tr>
        <th>
            Name(Quantity)
        </th>
        <th>
            Artist
        </th>
        <th>
            Genre
        </th>
        <th>
            Price
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.musicList)
    {



        <tr>
            <td>
                <img src=~/@item.ImageUrl width="100" height="100" alt="Image not Available" />
                @Html.DisplayFor(modelItem => item.Name)
                (@item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Artist)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.ActionLink("Delete", "DeleteFromCart", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<div style="font-size:20px">
    <strong><b>Grand Total = @MusicInventory.Controllers.Repository.grand_total</b></strong>
</div>
<div style="font-size:22px">
    <strong><b>@Html.ActionLink("Start Shopping Again!", "DeleteAll")</b></strong>
</div>

MusicInventory/MusicInventory/Views/Musics/Create.cshtml
@model MusicInventory.Models.Music

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Music</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Artist, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Artist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Artist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MusicInventory/MusicInventory/Views/Musics/Delete.cshtml
@model MusicInventory.Models.Music

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Music</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Artist)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MusicInventory/MusicInventory/Views/Musics/DeleteAll.cshtml
@{
    ViewBag.Title = "DeleteAll";
}

<h2>DeleteAll</h2>

MusicInventory/MusicInventory/Views/Musics/Details.cshtml
@model MusicInventory.Models.Music

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div class="row">
<div class="col-md-6">
    <h4>Music</h4>
    <hr />
    <img src=~/@Model.ImageUrl width="100" height="100" alt="Image Not Available"/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
            
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Artist)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>
</div>
    </div>
<p>
    <div style="font-size:18px">
        @Html.ActionLink("Add to Cart", "AddToCart", new { id = Model.Id })
        @Html.ActionLink("Back to List", "Index")
    </div> 
   
    
</p>

MusicInventory/MusicInventory/Views/Musics/DisplayAllGenres.cshtml
@model IEnumerable<string>

@{
    ViewBag.Title = "DisplayGenre";
}

<h2>Available Genres</h2>
    <div class="col-md-1">
        <table>
        @foreach (var item in Model)
        {
            <tr>
                <td style="font-size:28px">
                    @Html.ActionLink(item, "Index", new { id = item })
                </td>

            </tr>
        }
            </table>
    </div>

MusicInventory/MusicInventory/Views/Musics/Edit.cshtml
@model MusicInventory.Models.Music

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Music</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Artist, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Artist, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Artist, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MusicInventory/MusicInventory/Views/Musics/Foo.cshtml
    <h3>Foo</h3>

MusicInventory/MusicInventory/Views/Musics/Index.cshtml
@model IEnumerable<MusicInventory.Models.Music>

@{
    ViewBag.Title = "Index";
}
<style>
    img{
        border-radius:50%;
    }
</style>
<h2>Index</h2>
<div class="row">
    <div class="col-lg-8">
        <centre><img src="~/Content/Images/les.jpg" width="1200" height="600" alt="Image Not Found" /></centre>
    </div>
</div>

<div>
<div>
    <br /><br /><br />
<div class="row">
        <div class="row" style="font-size:18px">
            Fresh Out of the Box!!!
        </div>
        @{
            foreach (var item in Model)
            {
                <div class="col-md-4">
                            <div class-="well">
                                <img src=~/@item.ImageUrl width="100" height="100" />
                            </div>
                
                <div>
                    <b>@Html.ActionLink(item.Name, "Details", new { id = item.Id })</b> 
                </div>
                </div>
                
            }
        }

    </div>
    </div>
</div>

MusicInventory/MusicInventory/Views/Musics/ShowCart.cshtml
@model MusicInventory.Models.MusicList

@{
    ViewBag.Title = "ShowCart";
}
<style>

img{
    border-radius:70%;
}

</style>
<div id="resDiv">
    <h2>ShowCart</h2>
    <table class="table" id="res">
        <tr>
            <th>
                Name(Quantity)
            </th>
            <th>
                Artist
            </th>
            <th>
                Genre
            </th>
            <th>
                Price
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.musicList)
        {
            <tr id=@item.Id>
                <td>
                    <img src=~/@item.ImageUrl width="100" height="100" alt="Image not Available" />
                    @Html.DisplayFor(modelItem => item.Name)
                    (@item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Artist)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    <div class="a">

                    @(Ajax.ActionLink("Remove", "DeleteFromCart", new { id = item.Id },
                                                new AjaxOptions
                                                {
                                                    UpdateTargetId = "resDiv",
                                                    InsertionMode = InsertionMode.Replace,
                                                    HttpMethod = "POST"
                                                }
                                                ))
                    </div>


                </td>
            </tr>
        }

    </table>

    <div class="body-content">
        <div class="row" style="font-size:20px">
            <input type="button" value="Check Out" onclick="location.href='@Url.Action("CheckOut", "Musics" )'" />

            @*@Html.ActionLink("Check Out", "CheckOut")*@
        </div>
    </div>

</div>



@section Scripts{
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js");
    }

MusicInventory/MusicInventory/Views/Musics/ShowDetailsPartialView.cshtml
@model MusicInventory.Models.MusicList

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Artist)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Artist)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageUrl)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>